name: Asunciongourmet
favicon: null
layout_spectrum: 0.68322
typography_spectrum: 0.47517
title: Asunciongourmet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffb93f'
    - '#d47e03'
    - '#322300'
    - '#7c4500'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
