name: Asunciongourmet
favicon: null
layout_spectrum: 0.68322
typography_spectrum: 0.551320584025234
title: Asunciongourmet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4375
  lightness: 0.11563717410899699
  saturation: 0.9225294149946421
  rhythmicContrast: 0.9929218250326812
purpose: []
